### ISSUE TITLE
invalid required factory count

### ISSUE THREAD

**Issue by kubanka-peter** [lgfrbcsgo/du-factory-generator#50]
First: it's awesome, but it has some calculation error and you have to fix it

I tested it with "Glass Panel M" 2 assemblers and maintain 1500, 
- your calculator says that I need 2x 3d printer (Basic casing xs) => 2/min
- in reality I need 6x 3d printer to produce the required Basic Casing xs => 8/min

Another test, what i dont built justs I used https://hq.hyperion-corporation.de to see the values:
Basic Atmospheric Engine L - 2 assemblers and maintain 10,
- your calculator says that I need 3 steel smelter, but hyperion calculator says that 1 is enough.

**Comment by lgfrbcsgo** [comment]
> First: it's awesome, but it has some calculation error and you have to fix it
> 
> I tested it with "Glass Panel M" 2 assemblers and maintain 1500,
> 
> * your calculator says that I need 2x 3d printer (Basic casing xs) => 2/min
> * in reality I need 6x 3d printer to produce the required Basic Casing xs => 8/min

We need to investigate that. That seems to be a bug.

> Another test, what i dont built justs I used https://hq.hyperion-corporation.de to see the values:
> Basic Atmospheric Engine L - 2 assemblers and maintain 10,
> 
> * your calculator says that I need 3 steel smelter, but hyperion calculator says that 1 is enough.

That is by design. All industries should be able to run at 100% utilization 24/7. That allows us to easily add to an existing factory. We have some ideas on how to minimize the number of industries, but that's not a priority right now.

**Comment by tvwenger** [comment]
@kubanka-peter thanks for raising your concerns! Following up on what @lgfrbcsgo said:

> First: it's awesome, but it has some calculation error and you have to fix it
> 
> I tested it with "Glass Panel M" 2 assemblers and maintain 1500,
> 
>     * your calculator says that I need 2x 3d printer (Basic casing xs) => 2/min
> 
>     * in reality I need 6x 3d printer to produce the required Basic Casing xs => 8/min

Thanks for finding this bug! This is a typo in the recipe for "Glass Panel M" (says it requires only 1 Basic Casing XS instead of 4).

> Another test, what i dont built justs I used https://hq.hyperion-corporation.de to see the values:
> Basic Atmospheric Engine L - 2 assemblers and maintain 10,
> 
>     * your calculator says that I need 3 steel smelter, but hyperion calculator says that 1 is enough.

As @lgfrbcsgo said, this is by design in our factory. We want all industries to be able to run at 100% at all times. That one Steel smelter is enough to feed the Reinforced Frame, Combustion Chamber, and Basic Screw assemblers for the Basic Atmo Engine, but that's it. If you try to add any other outputs or expand the factory later, then there is going to be a bottleneck in your factory. For example:

* You setup your factory to produce Basic Atmo Engine with one Steel smelter.
* Later, you decide to add a bunch of other outputs to the factory. Now you need to send Basic Screws to some other industries.
* Your one Steel smelter isn't able to produce enough steel to feed that Basic Screw industry anymore. Now you have two options: (1) Add another Steel smelter that feeds into the existing Basic Screw industry, or (2) Add another Steel smelter and Basic Screw industry.
* The case of (2) is obviously worse that what our algorithm does, because it requires an extra industry and the existing industry isn't running near 100% capacity.
* The case of (1) would work, only if the existing Steel container has available input links. In large factories where all Steel input links are used up, then you would need to build another Steel container and link the new Steel container to the existing Basic Screw industry. Now you have two Steel containers linked to the same industry, and the mechanics of Dual Universe make it so the industry draws from the first one until its empty before it starts drawing from the second one. It does not draw from both containers equally. This will cause a bottleneck.

**Comment by d6rks1lv3rz3r0** [comment]
I would just point out here for the future, and maybe in the readme that this is **NOT** a crafting calculator. It doesn't give you the laziest way to quickly achieve your end goal. It is a factory generator, so it will give you **THE optimum** way to create a factory that will produce things exactly to your specs. 

I am saying this because I have been using this approach since the beginning of industries (as opposed to the quickest way, or the intractably inefficient Factorio based approaches (over feeding lines) with thousands of transfer units). However I kept getting hounded to the point of abuse about why Dual.SH or Hyperion would say different things ("yeah you are the only smart person here" .. I guess I was lol where were you two @tvwenger @lgfrbcsgo ahahahaha).
