### ISSUE TITLE
Use ore containers as final product containers

### ISSUE THREAD

**Issue by lgfrbcsgo** [lgfrbcsgo/du-factory-generator#8]

**Comment by tvwenger** [comment]
What does this mean?

**Comment by lgfrbcsgo** [comment]
That was a feature request from u/Blackout_AU. The idea was to reduce the number of ore and final product containers. The factory would produce in a circle when this option is checked. It would place the final product in the ore container.

**Comment by tvwenger** [comment]
I don't like this idea. It breaks the general organization of the factory where every container only contains a single type of item. If someone wants to set up their factory like this, it is a very simple change for them to implement (just link the final industries to the ore containers instead of the output containers).

**Comment by tvwenger** [comment]
Closing because this isn't a highly requested feature.
